name: CI Agent

on:
  push:
    branches:
      - main
    paths:
      - "agent/**"
      - ".github/workflows/ci-agent.yml"
  pull_request:
    branches:
      - main
    paths:
      - "agent/**"
      - ".github/workflows/ci-agent.yml"

defaults:
  run:
    working-directory: agent

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: agent/go.mod
          cache-dependency-path: agent/go.sum
      - name: Run Lint
        run: make lint

  test:
    name: Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: agent/go.mod
          cache-dependency-path: agent/go.sum
      - name: Run Tests with Coverage
        run: make test-coverage
      - name: Upload Coverage
        uses: codecov/codecov-action@v5
        with:
          files: agent/build/coverage.xml
          flags: agent
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: agent/go.mod
          cache-dependency-path: agent/go.sum
      - name: Build all platforms
        run: make build
